-- Migration to add manual PIX fields

ALTER TABLE weddings
ADD COLUMN manual_pix_type text,
ADD COLUMN manual_pix_key text;

-- Update the wedding_config view to include the new fields
DROP VIEW IF EXISTS wedding_config;
CREATE VIEW wedding_config AS
SELECT 
  id,
  user_id,
  couple_name,
  partner1_name,
  partner2_name,
  wedding_date,
  tagline,
  slug,
  layout,
  section_about,
  section_wedding_info,
  section_gifts,
  section_rsvp,
  section_message_wall,
  section_gallery,
  section_video,
  section_dress_code,
  hero_image_url,
  video_url,
  ceremony_date,
  ceremony_time,
  ceremony_location,
  ceremony_address,
  reception_location,
  reception_address,
  reception_time,
  same_location,
  about_text,
  dress_code_text,
  colors_to_avoid,
  additional_info,
  mercado_pago_public_key,
  payment_credit_card,
  payment_pix,
  payment_boleto,
  max_installments,
  story_photo_1,
  story_photo_2,
  story_photo_3,
  created_at,
  updated_at,
  manual_pix_type,
  manual_pix_key
FROM weddings;

-- Update the wedding_config_safe view (public read)
DROP VIEW IF EXISTS wedding_config_safe;
CREATE VIEW wedding_config_safe AS
SELECT 
  id,
  user_id,
  couple_name,
  partner1_name,
  partner2_name,
  wedding_date,
  tagline,
  slug,
  layout,
  section_about,
  section_wedding_info,
  section_gifts,
  section_rsvp,
  section_message_wall,
  section_gallery,
  section_video,
  section_dress_code,
  hero_image_url,
  video_url,
  ceremony_date,
  ceremony_time,
  ceremony_location,
  ceremony_address,
  reception_location,
  reception_address,
  reception_time,
  same_location,
  about_text,
  dress_code_text,
  colors_to_avoid,
  additional_info,
  mercado_pago_public_key,
  payment_credit_card,
  payment_pix,
  payment_boleto,
  max_installments,
  story_photo_1,
  story_photo_2,
  story_photo_3,
  created_at,
  updated_at,
  manual_pix_type,
  manual_pix_key
FROM weddings;
